check for .env file first

diff --git a/scripts/start b/scripts/start
--- a/scripts/start
+++ b/scripts/start
@@ -1,5 +1,14 @@
 #!/bin/bash
 
+
+if [ ! -f .env ]; then
+    echo ".env file not found! please create one and try again"
+    exit 1
+fi
+
+
+
+
 nohup_flag=''
 docker_flag=''
 
